### ISSUE TITLE
master does not compile — four merges landed code never built in combination

### ISSUE THREAD

**Issue by srpatcha** [embeddedos-org/eos#92]
`master` does not compile. Verified today from a fresh `git clone --depth 1`, no
local state:

```
kernel/src/sync.c:66:21:  error: 'mtx_t' has no member named 'original_prio'
kernel/src/sync.c:149:9:  error: implicit declaration of function 'task_valid'
kernel/src/sync.c:150:9:  error: 'g_blocked_on' undeclared
kernel/src/sync.c:197:13: error: 'g_blocked_on' undeclared
kernel/src/sync.c:206:5:  error: implicit declaration of function 'pi_propagate'
kernel/src/sync.c:225:13: error: 'g_blocked_on' undeclared
gmake[2]: *** [CMakeFiles/eos_kernel.dir/.../sync.c.o] Error 1

kernel/src/task.c:576:6:  error: redefinition of 'eos_task_set_current_internal'

build exit: 2
```

Nothing downstream can be trusted while this holds. No test result from `master`
is meaningful, no footprint number is real, and every open PR's "green" CI
measured the PR branch, not the result of merging it.

## How it happened

Four PRs each passed on their own branch and were squash-merged onto a base that
had moved underneath them. Nothing re-ran the suite on the merged result, so the
combination was never built by anything before it reached `master`.

`sync.c` is the clearest case: #55 and #67 implemented priority inheritance with
**incompatible designs** — one keeping `original_prio` on the mutex, the other
keeping `g_blocked_on` alongside `pi_propagate()`. Squashing both spliced halves
of each together. The result references fields and functions that no version of
the file ever defined at the same time. Neither PR was wrong; the merge was never
compiled.

`eos_task_set_current_internal` is the same failure in miniature: two merges each
added the definition, neither saw the other.

## This is a process defect, not four coding defects

The repository has no required status check:

```
$ gh api repos/embeddedos-org/eos/branches/master/protection
{"checks": null, "reviews": 1, "sigs": false}
```

`required_status_checks` is `null`. Nothing verifies that a merge result builds
before it becomes `master`. Branch protection asks for one approving review and
nothing else, so a green PR branch is sufficient to land code that has never been
compiled in the form it lands in.

This will recur on the next pair of overlapping PRs regardless of how carefully
the four current breakages are repaired.

## Work

- #82 repairs all four breakages and returns the suite to 30/30 plus a clean
  Cortex-M4 cross-build. It is `MERGEABLE`, and `BLOCKED` only because it wants
  one approving review and I authored it.
- The durable fix is a required status check on `master` that builds and tests
  the **merge result**. Once #82 lands, the existing workflow can be marked
  required; a PR whose merge would break the build then cannot merge, which is
  precisely what did not happen four times here.

## Order

#82 first. Every other open PR is stacked behind it — merging anything onto a
red base reproduces the exact conditions that caused this, and its CI result
would again describe a branch rather than a result.

**Comment by srpatcha** [comment]
The four breakages are repaired. `master` builds and tests clean — verified from
a fresh `git clone --depth 1`:

```
0 build errors
100% tests passed, 0 tests failed out of 28
```

`sync.c`, `task.c`, the duplicate crypto test targets — all gone.

**Leaving this open**, because the defect this issue is actually about is
untouched:

```
$ gh api repos/embeddedos-org/eos/branches/master/protection
{"checks": null, "reviews": 1, "sigs": false}
```

`required_status_checks` is still `null`. Nothing builds the merge result before
it becomes `master`. Four individually-green PRs combined into code that had
never been compiled in the form it landed in, and the conditions that allowed
that are exactly as they were.

Now is the cheapest moment to close it: the build is green, so marking the
existing workflow required costs nothing today and refuses the next PR whose
merge would break it. Waiting until it breaks again means doing this repair a
second time first.

The same gap is open in ebuild (#87 there) and eBoot — `checks=null` on all
three.

This issue can close when there is a required check on `master`, not before.

**Comment by srpatcha** [comment]
Third instance, and this one is mine.

`master` stopped compiling again:

```
tests/test_net.c:212:5: error: implicit declaration of function 'assert'
build errors: 4
```

From #89, which I wrote. `tests/test_net.c` calls `assert()` without including
`<assert.h>`; it worked on the development branch because the symbol arrived
transitively through another header, and stopped working once the file landed
next to a different set of includes. Repaired in #124 — one line, 34/34 passing.

The tally on this issue is now:

1. Four merges landing code never compiled in combination — `sync.c` splicing two
   incompatible priority-inheritance designs.
2. ebuild's `dispatch.py` orphan `else:`, breaking every command (#87 there).
3. This.

Different authors, different mistakes, one cause:

```
$ gh api repos/embeddedos-org/eos/branches/master/protection
{"checks": null, "reviews": 1, "sigs": false}
```

I have been filing this gap against other people's merges all week and it has now
caught me, in the most ordinary way available — a transitive include that existed
on my branch and not on the result. That is the case *for* the gate rather than
against the author. Nobody audits every transitive include by hand; a machine
does it for nothing.

The build is green again as of #124. That makes right now the cheapest possible
moment to mark the existing workflow required on `master` — it is a settings
change, it costs nothing today, and it forecloses this exact failure. Waiting
means repairing a fourth instance first.
